export const CATEGORY_CHOSEN = 'CATEGORY_CHOSEN';
export const TODO_CHOSEN = 'TODO_CHOSEN';
export const TODO_DRAGGED = 'TODO_DRAGGED';
export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED';
export const TODOS_FETCHED = 'TODOS_FETCHED';